namespace Scoop.Transpiling
{
    public static class Formatting
    {
        public const string GeneratedPreamble = @"
//-----------------------------------------------------------------------------
//  This file has been automatically generated by {0} 
//  from source in:
//    {1}
//  Do not edit this file by hand, any changes will be overridden when the 
//  file is regenerated.
//-----------------------------------------------------------------------------
";

        public static string GetGeneratedFilePreamble(string compiler, string file)
        {
            return string.Format(GeneratedPreamble, compiler, file);
        }
    }
}