
//-----------------------------------------------------------------------------
//  This file has been automatically generated by Scoop L1 
//  from source in:
//    MyClass.scl1
//  Do not edit this file by hand, any changes will be overridden when the 
//  file is regenerated.
//-----------------------------------------------------------------------------

// Source File: MyClass.scl1
namespace Scoop.Example
{
    public sealed class MyClass 
    {
        public MyClass()
        {
            // Do not allow concrete inheritance
            System.Diagnostics.Debug.Assert(GetType().BaseType == typeof(object));
            
        }

        public void MyMethod()
        {
        }
    }
}
